In [1]:
import numpy as np


dataset = np.array([
    162, 52, 142, 62, 128, 21,
    105, 69, 189, 95, 53, 33,
    3, 3, 176, 46, 116, 3,
    128, 80, 160, 35, 124, 52,
    35, 78, 124, 39, 98, 107,
    181, 29, 57, 25, 93, 62
])

In [2]:
sorted_dataset = sorted(dataset)

# 全距
total_range = sorted_dataset[-1] - sorted_dataset[0]

# 組數
group_num = 8

# 組距
# group_range = round(total_range / group_num)
group_range=  25
print(total_range, group_range)

# center
center = group_range / 2

186 25

In [4]:
import pandas as pd

group_range_set = []
n = 0
for i in range(group_num):
    last_n = n + 1
    n += group_range
    group_range_set.append((round(last_n), round(n)))

group_limit_set = []
for (b, t) in group_range_set:
    group_limit_set.append((b-0.5, t+0.5))

center_set = []
for (b, t) in group_limit_set:
    center_set.append(int((t-b)/2))

count_set = []
for (b, t) in group_limit_set:
    count = 0
    for d in dataset:
        if b <= d <= t:
            count += 1
    count_set.append(count)

total_count = sum(count_set)
rel_count_set = list(map(lambda x: round(x/total_count, 2), count_set))
print(sum(rel_count_set))

df = pd.DataFrame(
    {
        '組距': group_range_set,
        '組界': group_limit_set,
        '組中點': center_set,
        '組次數': count_set,
        '相對次數': rel_count_set
    }
)

display(df)

0.9999999999999999

           組距              組界  組中點  組次數  相對次數
0     (1, 25)     (0.5, 25.5)   12    5  0.14
1    (26, 50)    (25.5, 50.5)   12    6  0.17
2    (51, 75)    (50.5, 75.5)   12    7  0.19
3   (76, 100)   (75.5, 100.5)   12    5  0.14
4  (101, 125)  (100.5, 125.5)   12    5  0.14
5  (126, 150)  (125.5, 150.5)   12    3  0.08
6  (151, 175)  (150.5, 175.5)   12    2  0.06
7  (176, 200)  (175.5, 200.5)   12    3  0.08